##### Menu
menu:
  home: /
  archives: /archives
  about: /page/profile.html
  笔记: http://read.lingyu.wang/
  日记: /everyday

##### Author information
feed: atom ##eg: 'atom' will be '/atom.xml'
github: lingyucoder ##eg: 'git_name' will be 'http://github.com/git_name'
weibo: lingyucoder ##eg: 'weibo_name' will be 'http://weibo.com/weibo_name'
twitter: lingyucoder ##eg: 'twitter_name' will be 'http://twitter.com/twitter_name'
facebook: ##eg: 'facebook_name' will be 'http://facebook.com/facebook_name'

##### Avatar
avatar: 
  enable: true ##if false, the avatar will be hidden
  link: /page/profile.html ##where to go when the avatar is clicked
  image: images/avatar.jpg ##the picture

##### Google Analytics
google_analytics: 
  enable: false
  id: UA-51090540-1 ##your google analytics ID
  site: http://plugins.lingyu.wang ##your site

##### Baidu Analytics
baidu_tongji:
  enable: true
  id: a5aa4945a04cc5a5a4cd6835ccb7d419 ##your baidu analytics ID

##### duoshuo comments
duoshuo:
  enable: true
  short_name: skyinlayer ##your duoshuo short name

##### disqus comments
disqus:
  enable: false
  short_name: ##your disqus short name

##### jiathis
jiathis:
  enable: true
  id: 1409314953297200 ##your jiathis user ID

##### widgets
widgets:
- recents
- categories
- tags
- archieves

##provide four widgets:
## recents: recent five posts
## tags: all tags
## categories: all categories
## friends: your friends links
## archieves: all your posts


##### friends links
friends:
  博客: http://lingyu.wang


