categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Previous
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
friends: Links
read_more: Read More
home: Home
about: About
archives: Archives
time_format: YYYY-MM-DD
archives_time_format: YYYY-M